---
apiVersion: v1
data:
mapRoles:
  - groups:
    - system: bootstrappers
    - system: nodes
    rolearn: arn:aws:iam::00000000:role/eksNodeRole
    username: system: node: ({EC2PrivateDNSName}}
mapUsers:
  - groups:
    - shopping_services_dev_team
    userarn: arn:aws:iam::00000000:user/user_from_shopping_svc
    username: user_from_shopping_svc
  - groups:
    - order_delivery_dev_team
    userarn: arn:aws:iam::490601043575:user/user_from_delivery_svc
    username: user_from_delivery_svc
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
