---
apiVersion: rbac.authorization.k8s.i0/v1
kind: ClusterRole
metadata:
  name: superuser
rules:
  - apiGroups:
    - ""
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - "apps"
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
