AlertRecipient:
  - dev-ops@company.com
kb_release_days:
  'days': 30

Fitler_status:
  'filter': True
  'MsrcSeverity': "Critical"

Filter:
  'Product': ['WindowsServer2008R2', 'WindowsServer2012R2', 'WindowsServer2008', 'WindowsServer2016', 'WindowsServer2019']
